baseURL: https://ryancranie.com

languageCode: en

title: Ryan Cranie

copyright: © Copyright 2025 Ryan Cranie

theme: academic-folio

enableEmoji: true

enableRobotsTXT: true

publishDir: "../docs/"

# markup:
#   goldmark:
#     parser:
#       wrapStandAloneImageWithinParagraph: false
#       attribute:
#         block: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      image: true
  highlight:
    guessSyntax: true
    style: dracula  # syntax highlighting style for markdown code blocks
                    # choose a style from https://xyproto.github.io/splash/docs/all.html

module:
  imports:
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
