baseURL = "https://www.ryancranie.com/"
languageCode = "en-gb"
title = "Ryan Cranie"
theme = "ryancranie"
enableRobotsTXT = false
disableKinds = ["taxonomy", "term"]

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "portfolio"
url = "/it-portfolio/"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 3

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4
