main:
- name: Education
  url: "#education"
  weight: 2

- name: Research
  url: "#research"
  weight: 3

- name: Projects
  url: "#projects"
  weight: 4

- name: Work
  url: "#work"
  weight: 5

- name: Skills
  url: "#skills"
  weight: 6

- name: Achievements
  url: "#achievements"
  weight: 7

- name: CV
  url: "https://cv.ryancranie.com/"
  weight: 8

social:
- name: email
  url: mailto:mail@ryancranie.com
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://www.linkedin.com/in/ryancranie
  weight: 2
  params:
    icon: fab fa-linkedin

- name: GitHub
  url: https://github.com/ryancranie
  weight: 3
  params:
    icon: fab fa-github

- name: Notes
  url: https://notes.ryancranie.com
  weight: 4
  params:
    icon: fas fa-book-open

